//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSchoolM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int S_id { get; set; }
        public string S_name { get; set; }
        public string S_class { get; set; }
        public string S_subject { get; set; }
    }
}
